/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { FornecedorDTO } from '../model/fornecedorDTO';
import { PageFornecedorDTO } from '../model/pageFornecedorDTO';
import { ResponseFornecedorDTO } from '../model/responseFornecedorDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FornecedorControllerService {

    protected basePath = 'http://localhost:8080/cachacaria-api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deleteById
     * 
     * @param fornecedorId fornecedorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteByIdUsingDELETE(fornecedorId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteByIdUsingDELETE(fornecedorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteByIdUsingDELETE(fornecedorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteByIdUsingDELETE(fornecedorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fornecedorId === null || fornecedorId === undefined) {
            throw new Error('Required parameter fornecedorId was null or undefined when calling deleteByIdUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/fornecedores/fornecedor/${encodeURIComponent(String(fornecedorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findAll
     * 
     * @param pag pag
     * @param ord ord
     * @param dir dir
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findAllUsingGET(pag?: number, ord?: string, dir?: string, observe?: 'body', reportProgress?: boolean): Observable<PageFornecedorDTO>;
    public findAllUsingGET(pag?: number, ord?: string, dir?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageFornecedorDTO>>;
    public findAllUsingGET(pag?: number, ord?: string, dir?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageFornecedorDTO>>;
    public findAllUsingGET(pag?: number, ord?: string, dir?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pag !== undefined && pag !== null) {
            queryParameters = queryParameters.set('pag', <any>pag);
        }
        if (ord !== undefined && ord !== null) {
            queryParameters = queryParameters.set('ord', <any>ord);
        }
        if (dir !== undefined && dir !== null) {
            queryParameters = queryParameters.set('dir', <any>dir);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<PageFornecedorDTO>(`${this.basePath}/fornecedores/fornecedores`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findByCnpj
     * 
     * @param fornecedorCnpj fornecedorCnpj
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByCnpjUsingGET(fornecedorCnpj: string, observe?: 'body', reportProgress?: boolean): Observable<ResponseFornecedorDTO>;
    public findByCnpjUsingGET(fornecedorCnpj: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseFornecedorDTO>>;
    public findByCnpjUsingGET(fornecedorCnpj: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseFornecedorDTO>>;
    public findByCnpjUsingGET(fornecedorCnpj: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fornecedorCnpj === null || fornecedorCnpj === undefined) {
            throw new Error('Required parameter fornecedorCnpj was null or undefined when calling findByCnpjUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ResponseFornecedorDTO>(`${this.basePath}/fornecedores/fornecedor/cnpj/${encodeURIComponent(String(fornecedorCnpj))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findById
     * 
     * @param fornecedorId fornecedorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByIdUsingGET(fornecedorId: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseFornecedorDTO>;
    public findByIdUsingGET(fornecedorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseFornecedorDTO>>;
    public findByIdUsingGET(fornecedorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseFornecedorDTO>>;
    public findByIdUsingGET(fornecedorId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fornecedorId === null || fornecedorId === undefined) {
            throw new Error('Required parameter fornecedorId was null or undefined when calling findByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ResponseFornecedorDTO>(`${this.basePath}/fornecedores/fornecedor/id/${encodeURIComponent(String(fornecedorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * save
     * 
     * @param fornecedorDTO fornecedorDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveUsingPOST(fornecedorDTO: FornecedorDTO, observe?: 'body', reportProgress?: boolean): Observable<ResponseFornecedorDTO>;
    public saveUsingPOST(fornecedorDTO: FornecedorDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseFornecedorDTO>>;
    public saveUsingPOST(fornecedorDTO: FornecedorDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseFornecedorDTO>>;
    public saveUsingPOST(fornecedorDTO: FornecedorDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fornecedorDTO === null || fornecedorDTO === undefined) {
            throw new Error('Required parameter fornecedorDTO was null or undefined when calling saveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseFornecedorDTO>(`${this.basePath}/fornecedores/`,
            fornecedorDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param fornecedorDTO fornecedorDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT(fornecedorDTO: FornecedorDTO, observe?: 'body', reportProgress?: boolean): Observable<ResponseFornecedorDTO>;
    public updateUsingPUT(fornecedorDTO: FornecedorDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseFornecedorDTO>>;
    public updateUsingPUT(fornecedorDTO: FornecedorDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseFornecedorDTO>>;
    public updateUsingPUT(fornecedorDTO: FornecedorDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fornecedorDTO === null || fornecedorDTO === undefined) {
            throw new Error('Required parameter fornecedorDTO was null or undefined when calling updateUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ResponseFornecedorDTO>(`${this.basePath}/fornecedores/`,
            fornecedorDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
